== Adresses des ports

Pour ceux qui construisent leur matériel, il est facile et
économique d'augmenter le nombre d'entrées sorties d'un PC en lui
ajoutant une carte PCI fournissant un ou deux ports parallèles
supplémentaires. Faire suivre ces ports d'une couche
d'opto-isolation est utile pour éviter les courts circuits pouvant
détruire la carte, voir même toute la carte mère. LinuxCNC supporte un
maximum de 8 ports parallèles.

Certaines parmi les bonnes cartes parallèles sont à base de
chipset Netmos. Elles fournissent un signal +5V bien propre, elles
fournissent un ou deux ports parallèles.

Pour trouver les adresses d'entrées/sorties de ces cartes, ouvrir
une console et utiliser la commande en ligne:

----
lspci -v
----

Rechercher ensuite dans la liste de matériel fourni, le nom du
chipset de la nouvelle carte, dans cette exemple c'est l'entrée
NetMos Technology pour une carte à deux ports:

----
0000:01:0a.0 Communication controller: \
      Netmos Technology PCI 9815 Multi-I/O Controller (rev 01)
      Subsystem: LSI Losgic / Symbios Logic 2POS (2 port parallel adapter)
      Flags: medium devsel, IRQ 5
      I/O ports at b800 [size=8]
      I/O ports at bc00 [size=8]
      I/O ports at c000 [size=8]
      I/O ports at c400 [size=8]
      I/O ports at c800 [size=8]
      I/O ports at cc00 [size=16]
----

Après expérimentation, il se trouve que le premier port (incorporé
à la carte) utilise la troisième adresse de la liste (c000) et le
deuxième port (raccordé par une nappe) utilise la première adresse
(b800).

Il est alors possible d'ouvrir dans l'éditeur le fichier .hal de la
machine et d'insérer l'adresse trouvée à l'endroit approprié.

----
loadrt hal\_parport cfg="0x378 0xc000"
----

Noter la présence des guillemets "" encadrant les deux adresses,
ils sont obligatoires dès qu'il y a plus d'une carte.

Il est nécessaire également d'ajouter les fonctions de lecture
(read) et d'écriture (write) pour la nouvelle carte. Par exemple:

----
addf parport.1.read base-thread 1
addf parport.1.write base-thread -1
----

Noter que les valeurs peuvent être différentes de celles de cet
exemple. Les cartes Netmos sont Plug-N-Play, elles peuvent donc
changer leur adressage selon le connecteur PCI dans lequel elles
sont placées. Si l'installation des cartes PCI de
la machine est modifiée, ne pas oublier de vérifier leurs adresses avant de
lancer LinuxCNC.

