# po4a Version 0.57 in ubuntu 20 do not write translated adoc as
# UTF-8.  Need at least version 0.62 to fix it.
# Motivations to update:
#   0.66 to also get fix for empty asciidoc table cells.
#   0.67 for hard newlines ( +\n) in paragraphs
name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  rip-and-test:
    runs-on: ubuntu-20.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - run: git fetch --recurse-submodules=no https://github.com/linuxcnc/linuxcnc refs/tags/*:refs/tags/*
    - name: Build RIP & test
      run: |
        ./scripts/travis-install-build-deps.sh
        sudo apt-get install -y eatmydata
        curl -O https://snapshot.debian.org/archive/debian/20220716T154603Z/pool/main/p/po4a/po4a_0.67-2_all.deb
        sudo apt install ./po4a_0.67-2_all.deb
        cd src
        eatmydata ./autogen.sh
        eatmydata ./configure --with-realtime=uspace --disable-check-runtime-deps
        eatmydata make -O -j$((1+$(nproc))) default pycheck V=1
        # Note that the package build covers html docs
        ../scripts/rip-environment runtests -p
    
  htmldocs:
    runs-on: ubuntu-20.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - run: git fetch --recurse-submodules=no https://github.com/linuxcnc/linuxcnc refs/tags/*:refs/tags/*
    - name: Build HTML docmentation
      run: |
        ./scripts/travis-install-build-deps.sh
        sudo apt-get install -y eatmydata
        curl -O https://snapshot.debian.org/archive/debian/20220716T154603Z/pool/main/p/po4a/po4a_0.67-2_all.deb
        sudo apt install ./po4a_0.67-2_all.deb
        cd src
        eatmydata ./autogen.sh
        eatmydata ./configure --with-realtime=uspace --disable-check-runtime-deps --enable-build-documentation=html
        eatmydata make -O -j$((1+$(nproc))) manpages
        eatmydata make -O -j$((1+$(nproc))) translateddocs
        eatmydata make -O -j$((1+$(nproc))) docs
        # Note that the package build covers html docs

  package:
    runs-on: ubuntu-20.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Build Debian package
      run: |
        set -x
        git fetch --recurse-submodules=no https://github.com/linuxcnc/linuxcnc refs/tags/*:refs/tags/*
        ./scripts/travis-install-build-deps.sh
        sudo apt-get install -y eatmydata
        curl -O https://snapshot.debian.org/archive/debian/20220716T154603Z/pool/main/p/po4a/po4a_0.67-2_all.deb
        sudo apt install ./po4a_0.67-2_all.deb
        codename=$(lsb_release -cs)
        dch --maintmaint --distribution $codename "GitHub test package."
        eatmydata debian/configure
        eatmydata debuild -us -uc -B
        eatmydata debuild -us -uc -A
        sudo apt-get install ../*.deb
        ./scripts/runtests -p tests/
        eatmydata lintian --info --display-info --pedantic --display-experimental ../linuxcnc*.changes
        mkdir built-debs
        cp ../linuxcnc*_* built-debs/
    - name: Archive generated PDF files
      uses: actions/upload-artifact@v3
      with:
        name: PDFs
        retention-days: 7
        path: docs/*.pdf
    - name: Archive generated Debian packages
      uses: actions/upload-artifact@v3
      with:
        name: debs
        retention-days: 7
        path: built-debs/*
